name: Bug Report
description: Report a bug in RCL language tools
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - CLI (@rcs-lang/cli)
        - Compiler (@rcs-lang/compiler)
        - Parser (@rcs-lang/parser)
        - Language Service (@rcs-lang/language-service)
        - VSCode Extension
        - IDE (@rcs-lang/ide)
        - CSM (@rcs-lang/csm)
        - AST (@rcs-lang/ast)
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a file with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: rcl-code
    attributes:
      label: RCL Code Sample
      description: If applicable, provide the RCL code that causes the issue
      render: rcl

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Any error messages or logs
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Node.js
        - Browser
        - VSCode
        - Other
      default: 0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: If applicable, what version of Node.js?
      placeholder: "20.0.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "macOS 14, Windows 11, Ubuntu 22.04"