import type * as monaco from 'monaco-editor';

// Catppuccin Latte (light theme) color palette
const latte = {
	rosewater: 'dc8a78',
	flamingo: 'dd7878',
	pink: 'ea76cb',
	mauve: '8839ef',
	red: 'd20f39',
	maroon: 'e64553',
	peach: 'fe640b',
	yellow: 'df8e1d',
	green: '40a02b',
	teal: '179299',
	sky: '04a5e5',
	sapphire: '209fb5',
	blue: '1e66f5',
	lavender: '7287fd',
	text: '4c4f69',
	subtext1: '5c5f77',
	subtext0: '6c6f85',
	overlay2: '7c7f93',
	overlay1: '8c8fa1',
	overlay0: '9ca0b0',
	surface2: 'acb0be',
	surface1: 'bcc0cc',
	surface0: 'ccd0da',
	base: 'eff1f5',
	mantle: 'e6e9ef',
	crust: 'dce0e8',
};

// Catppuccin Mocha (dark theme) color palette
const mocha = {
	rosewater: 'f5e0dc',
	flamingo: 'f2cdcd',
	pink: 'f5c2e7',
	mauve: 'cba6f7',
	red: 'f38ba8',
	maroon: 'eba0ac',
	peach: 'fab387',
	yellow: 'f9e2af',
	green: 'a6e3a1',
	teal: '94e2d5',
	sky: '89dceb',
	sapphire: '74c7ec',
	blue: '89b4fa',
	lavender: 'b4befe',
	text: 'cdd6f4',
	subtext1: 'bac2de',
	subtext0: 'a6adc8',
	overlay2: '9399b2',
	overlay1: '7f849c',
	overlay0: '6c7086',
	surface2: '585b70',
	surface1: '45475a',
	surface0: '313244',
	base: '1e1e2e',
	mantle: '181825',
	crust: '11111b',
};

export const rclLightTheme: monaco.editor.IStandaloneThemeData = {
	base: 'vs',
	inherit: true,
	rules: [
		{ token: 'keyword', foreground: latte.mauve, fontStyle: 'bold' },
		{ token: 'keyword.flow', foreground: latte.mauve, fontStyle: 'bold' },
		{ token: 'identifier.title', foreground: latte.blue },
		{ token: 'identifier.lower', foreground: latte.text },
		{ token: 'variable', foreground: latte.peach },
		{ token: 'variable.interpolation', foreground: latte.peach, fontStyle: 'italic' },
		{ token: 'constant', foreground: latte.mauve },
		{ token: 'constant.atom', foreground: latte.sapphire },
		{ token: 'attribute', foreground: latte.yellow, fontStyle: 'bold' },
		{ token: 'string', foreground: latte.green },
		{ token: 'string.quote', foreground: latte.green },
		{ token: 'string.escape', foreground: latte.pink, fontStyle: 'bold' },
		{ token: 'regexp', foreground: latte.red },
		{ token: 'number', foreground: latte.peach },
		{ token: 'embedded', foreground: latte.text, background: latte.surface0 },
		{ token: 'type.tag', foreground: latte.yellow },
		{ token: 'comment', foreground: latte.overlay1, fontStyle: 'italic' },
		{ token: 'operator', foreground: latte.sky },
		{ token: 'operator.arrow', foreground: latte.mauve },
		{ token: 'operator.spread', foreground: latte.mauve },
		{ token: 'delimiter', foreground: latte.overlay2 },
	],
	colors: {
		'editor.foreground': `#${latte.text}`,
		'editor.background': `#${latte.base}`,
		'editorCursor.foreground': `#${latte.rosewater}`,
		'editor.lineHighlightBackground': `#${latte.mantle}`,
		'editorLineNumber.foreground': `#${latte.overlay0}`,
		'editor.selectionBackground': `#${latte.surface2}`,
		'editor.inactiveSelectionBackground': `#${latte.surface1}`,
		'editorIndentGuide.background': `#${latte.surface1}`,
		'editorIndentGuide.activeBackground': `#${latte.surface2}`,
		'editorBracketMatch.background': `#${latte.surface2}`,
		'editorBracketMatch.border': `#${latte.mauve}`,
	},
};

export const rclDarkTheme: monaco.editor.IStandaloneThemeData = {
	base: 'vs-dark',
	inherit: true,
	rules: [
		{ token: 'keyword', foreground: mocha.mauve, fontStyle: 'bold' },
		{ token: 'keyword.flow', foreground: mocha.mauve, fontStyle: 'bold' },
		{ token: 'identifier.title', foreground: mocha.blue },
		{ token: 'identifier.lower', foreground: mocha.text },
		{ token: 'variable', foreground: mocha.peach },
		{ token: 'variable.interpolation', foreground: mocha.peach, fontStyle: 'italic' },
		{ token: 'constant', foreground: mocha.mauve },
		{ token: 'constant.atom', foreground: mocha.sapphire },
		{ token: 'attribute', foreground: mocha.yellow, fontStyle: 'bold' },
		{ token: 'string', foreground: mocha.green },
		{ token: 'string.quote', foreground: mocha.green },
		{ token: 'string.escape', foreground: mocha.pink, fontStyle: 'bold' },
		{ token: 'regexp', foreground: mocha.red },
		{ token: 'number', foreground: mocha.peach },
		{ token: 'embedded', foreground: mocha.text, background: mocha.surface0 },
		{ token: 'type.tag', foreground: mocha.yellow },
		{ token: 'comment', foreground: mocha.overlay1, fontStyle: 'italic' },
		{ token: 'operator', foreground: mocha.sky },
		{ token: 'operator.arrow', foreground: mocha.mauve },
		{ token: 'operator.spread', foreground: mocha.mauve },
		{ token: 'delimiter', foreground: mocha.overlay2 },
	],
	colors: {
		'editor.foreground': `#${mocha.text}`,
		'editor.background': `#${mocha.base}`,
		'editorCursor.foreground': `#${mocha.rosewater}`,
		'editor.lineHighlightBackground': `#${mocha.surface0}`,
		'editorLineNumber.foreground': `#${mocha.overlay0}`,
		'editor.selectionBackground': `#${mocha.surface2}`,
		'editor.inactiveSelectionBackground': `#${mocha.surface1}`,
		'editorIndentGuide.background': `#${mocha.surface1}`,
		'editorIndentGuide.activeBackground': `#${mocha.surface2}`,
		'editorBracketMatch.background': `#${mocha.surface2}`,
		'editorBracketMatch.border': `#${mocha.mauve}`,
	},
};

export function registerRclThemes(monacoInstance: typeof monaco): void {
	monacoInstance.editor.defineTheme('rcl-light', rclLightTheme);
	monacoInstance.editor.defineTheme('rcl-dark', rclDarkTheme);
}
