name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Java 17 (for ANTLR)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Proto
        uses: moonrepo/setup-proto@v1
        with:
          version: latest
          
      - name: Install tools via Proto
        run: proto install
          
      - name: Install dependencies
        run: bun install
        
      - name: Build packages
        run: moon run :build
        
      - name: Ensure parser is properly built
        run: |
          cd packages/parser
          echo "Force rebuilding parser to ensure imports are fixed..."
          rm -rf dist
          bun run tsc
          moon run parser:fix-js-imports
          echo "Checking RclLexer.js imports:"
          grep "import.*from" dist/generated/RclLexer.js | head -5
        
      - name: Run all tests
        run: moon run :test
        
      - name: Type check
        run: moon run :typecheck
        
      - name: Lint
        run: moon run :lint