name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Moon
        run: bun install -g @moonrepo/cli
        
      - name: Build packages
        run: moon run :build
        
      - name: Run all tests
        run: moon run :test
        
      - name: Type check
        run: moon run :typecheck
        
      - name: Lint
        run: moon run :lint