name: Sync Release Tags to Main

on:
  create:
    # Triggered when a tag is created

permissions:
  contents: write

jobs:
  sync-tag:
    # Only run if a version tag was created on the release branch
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/ast-v') || startsWith(github.ref, 'refs/tags/compiler-v') || startsWith(github.ref, 'refs/tags/cli-v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0
          
      - name: Checkout main branch
        run: |
          git fetch origin main:main
          
      - name: Get tag info
        id: tag_info
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          
          # Get the commit SHA that the tag points to
          TAG_SHA=$(git rev-list -n 1 $TAG_NAME)
          echo "tag_sha=$TAG_SHA" >> $GITHUB_OUTPUT
          
      - name: Cherry-pick version bump commit to main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Switch to main branch
          git checkout main
          
          # Find the version bump commit (usually the commit before the tag)
          VERSION_COMMIT=$(git log --oneline -n 20 ${{ steps.tag_info.outputs.tag_sha }} | grep -E "(chore: release|chore\(main\): release)" | head -1 | cut -d' ' -f1)
          
          if [ -n "$VERSION_COMMIT" ]; then
            echo "Found version bump commit: $VERSION_COMMIT"
            
            # Cherry-pick the version bump commit
            git cherry-pick $VERSION_COMMIT || {
              echo "Cherry-pick failed, attempting merge strategy"
              git cherry-pick --abort
              git checkout --theirs .
              git add .
              git commit -m "chore: sync version bump from release branch for ${{ steps.tag_info.outputs.tag_name }}"
            }
          else
            echo "No version bump commit found, skipping cherry-pick"
          fi
          
      - name: Tag main branch
        run: |
          # Create the same tag on main branch
          git tag -a ${{ steps.tag_info.outputs.tag_name }} -m "Release ${{ steps.tag_info.outputs.tag_name }}"
          
      - name: Push to main
        run: |
          git push origin main --tags
          
  notify:
    needs: sync-tag
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify sync status
        run: |
          if [ "${{ needs.sync-tag.result }}" == "success" ]; then
            echo "✅ Successfully synced release tag to main branch"
          else
            echo "⚠️ Failed to sync release tag to main branch - manual sync may be required"
          fi